johanhelsing/matchbox

- Cargo.lock
- matchbox_demo/Cargo.toml
- matchbox_demo/src/args.rs
- matchbox_server/Cargo.toml
- matchbox_server/src/args.rs
- matchbox_server/src/main.rs
> Upgrade to clap v3.0

- Cargo.lock
- matchbox_socket/Cargo.toml
- matchbox_socket/examples/connect_native.rs
- matchbox_socket/src/webrtc_socket/native/message_loop.rs
- matchbox_socket/src/webrtc_socket/wasm/message_loop.rs
I got #8 working by setting `negotiate` to `false` and then, in `handshake_accept`, using the data channel from the `on_data_channel` callback instead of creating one with `create_data_channel`.
> get "support native clients" pr working

- matchbox_socket/src/webrtc_socket/wasm/message_loop.rs
https://github.com/johanhelsing/matchbox/pull/16#issuecomment-1032510221
> Fix dropped trickle loop future on wasm

- matchbox_demo/src/main.rs
- matchbox_socket/src/ggrs_socket.rs
- matchbox_socket/src/lib.rs
Implement the ggrs trait directly on WebRtcSocket instead
Fixes: #22
> Remove WebRtcNonBlockingSocket

- matchbox_socket/src/lib.rs
- matchbox_socket/src/webrtc_socket/mod.rs
- matchbox_socket/src/webrtc_socket/native/message_loop.rs
- matchbox_socket/src/webrtc_socket/wasm/message_loop.rs
Implements #27 
This is my first public Rust contribution so I am happy about feedback especially about API conventions and borrow rules
I guess we should also add some tests - but right now I am not sure if this is even possible without major refactoring...
> Make ICE server URLs configurable

- matchbox_server/src/signaling.rs
The receiver might have disconnected (or someone is sending bogus for
some other reason)
> fix(server): Don't panic when signal receiver is unknown

- matchbox_socket/src/webrtc_socket/mod.rs
- matchbox_socket/src/webrtc_socket/native/message_loop.rs
- matchbox_socket/src/webrtc_socket/wasm/message_loop.rs
- ~~[ ] implement `From` trait for new enum~~
Fixes #3
> Add ice auth support

- README.md
- matchbox_socket/src/ggrs_socket.rs
- matchbox_socket/src/lib.rs
- matchbox_socket/src/webrtc_socket/mod.rs
And add #![warn(missing_docs)] at the crate level.
> docs: Rustdocs for everything!

- .github/workflows/ci.yml
- matchbox_demo/src/args.rs
Might be a drier way to do this with the matrix feature, but keep it simple stupid for now.
Closes: #52
> ci: Add wasm checks

- Cargo.lock
- matchbox_demo/Cargo.toml
@johanhelsing 
https://github.com/clap-rs/clap/issues/4510#issuecomment-1330021385
> Apply clap fix wasm32 support

- matchbox_socket/src/webrtc_socket/wasm/message_loop.rs
> Fix panic on wasm

- Cargo.lock
- matchbox_demo/Cargo.toml
- matchbox_demo/src/args.rs
- matchbox_demo/src/box_game.rs
- matchbox_demo/src/main.rs
- matchbox_socket/Cargo.toml
I know this is blocked on releases of ggrs and bevy_ggrs but I was curious what would be required to get this demo working using bevy 0.9 . Once I got it working I thought I might as well open a PR in case it's useful in the future.
XRef https://github.com/johanhelsing/matchbox/issues/55
> upgrade bevy to 0.9 in demo

- matchbox_server/src/main.rs
> Server: Update log target name

- .github/workflows/ci.yml
Add a CI job to build a docker container containing `matchbox_server` and publish it to Github Container Registry (`ghcr.io`) on tagged releases
> Build & Publish `matchbox_server` on tagged release

- matchbox_socket/src/ggrs_socket.rs
- matchbox_socket/src/webrtc_socket/mod.rs
- matchbox_socket/src/webrtc_socket/signal_peer.rs
> Remove commented out code

- matchbox_socket/src/webrtc_socket/mod.rs
> fixed document typo

- matchbox_socket/src/webrtc_socket/mod.rs
Added stun server fallback options
> chore: stun server fallback options

- matchbox_socket/src/lib.rs
I don't really see a reason not to.
> Forbid unsafe rust

- matchbox_server/src/signaling.rs
- matchbox_simple_demo/src/main.rs
- matchbox_socket/src/webrtc_socket/messages.rs
- matchbox_socket/src/webrtc_socket/mod.rs
- matchbox_socket/src/webrtc_socket/native/message_loop.rs
- matchbox_socket/src/webrtc_socket/native/signalling_loop.rs
- matchbox_socket/src/webrtc_socket/wasm/message_loop.rs
This supersedes #84 and closes #81. I used @rozgo's code as a base except:
- Removed the type complexity by using a struct as a parameter to pass channels
- Tidied the signalling server handle logic of disconnected peers
- Added signalling server disconnect test
> Disconnected peers

- matchbox_demo/src/box_game.rs
- matchbox_demo/src/main.rs
- matchbox_server/src/main.rs
- matchbox_server/src/signaling.rs
- matchbox_socket/src/webrtc_socket/mod.rs
- matchbox_socket/src/webrtc_socket/native/message_loop.rs
- matchbox_socket/src/webrtc_socket/wasm/message_loop.rs
- rustfmt.toml
Adds import granularity to the crate level, which closes #95.
Also adds a column limit, of 100 (which only affected some long, unwrapped comments in the demo).
> Add rustfmt

- matchbox_server/src/signaling.rs
- matchbox_socket/src/webrtc_socket/messages.rs
> Documentation enhancements

- Cargo.lock
- matchbox_simple_demo/Cargo.toml
- matchbox_simple_demo/src/main.rs
- Deserializes the blob packet into a string
- More documentation
- Replaced pretty_env_logger with tracing_subscriber for native
> Simple demo cleanup

- matchbox_socket/src/webrtc_socket/native/message_loop.rs
> Fixes native break on web client disconnect

- matchbox_socket/src/webrtc_socket/socket.rs
> Change default to only use 2 stun servers

- matchbox_socket/src/lib.rs
- matchbox_socket/src/webrtc_socket/messages.rs
- matchbox_socket/src/webrtc_socket/mod.rs
Publicizes:
- Packet
- MessageLoopFuture
> feat: publicize more types

- examples/bevy_ggrs/src/main.rs
Side-effects is that it will also help for debugging in #128
> add update_peers usage to bevy_ggrs example

- examples/bevy_ggrs/README.md
> Pass example arguments as values in readme snippet

- matchbox_socket/src/webrtc_socket/native.rs
Makes behaviour consistent between Wasm & Native by relying on data channel events to signal peer disconnection, resolving #131
> Remove redundant Native Peer status change handling

- matchbox_socket/src/webrtc_socket/socket.rs
> Fix panic on receive after socket future is dropped

- Cargo.lock
- examples/bevy_ggrs/src/box_game.rs
- matchbox_protocol/Cargo.toml
- matchbox_protocol/src/lib.rs
- matchbox_server/src/signaling.rs
- matchbox_socket/Cargo.toml
- matchbox_socket/src/ggrs_socket.rs
- matchbox_socket/src/webrtc_socket/mod.rs
- matchbox_socket/src/webrtc_socket/native.rs
- matchbox_socket/src/webrtc_socket/signal_peer.rs
- matchbox_socket/src/webrtc_socket/socket.rs
- matchbox_socket/src/webrtc_socket/wasm.rs
> Make `PeerId` a `Uuid` newtype

- matchbox_socket/src/webrtc_socket/native.rs
Alternative to #155 using `async` blocks
By wrapping the entire handshaking implementations in `.compat().await` and removing the low-level ones.
Fixes #152
> Fix native crash when connecting to wasm, async blocks

- matchbox_socket/Cargo.toml
- matchbox_socket/src/webrtc_socket/native.rs
Just some very minor formatting/logging cleanups
> Minor style/logging cleanups

- matchbox_socket/src/ggrs_socket.rs
- matchbox_socket/src/webrtc_socket/socket.rs
> Add channel type helpers to socker builder

- bevy_matchbox/Cargo.toml
Makes it just a litle bit easier to get started with bevy_ggrs and matchbox
> Add `ggrs` feature to `bevy_matchbox`

- Cargo.lock
- bevy_matchbox/Cargo.toml
- examples/bevy_ggrs/Cargo.toml
- examples/bevy_ggrs/src/box_game.rs
- examples/bevy_ggrs/src/main.rs
> Update bevy_matchbox and bevy_ggrs_example to Bevy 0.10

- Cargo.lock
- README.md
- bevy_matchbox/Cargo.toml
- matchbox_protocol/Cargo.toml
- matchbox_server/Cargo.toml
- matchbox_signaling/Cargo.toml
- matchbox_socket/Cargo.toml
> Release 0.6.0

- matchbox_server/Dockerfile
#197 
This produced a working image, which I've deployed over the broken on on dockerhub. Not sure I want to merge this, though, as it makes CI horrendously slow.
> Disable caching in docker image

- .github/workflows/code.yml
actions-rs no longer maintained: https://github.com/actions-rs/toolchain/issues/216
> ci: Switch to dtolnay/rust-toolchain

- bevy_matchbox/src/lib.rs
- matchbox_socket/src/webrtc_socket/error.rs
> bevy_matchbox doc error

- examples/bevy_ggrs/src/main.rs
- examples/simple/src/main.rs
- matchbox_protocol/src/lib.rs
- matchbox_server/src/signaling.rs
- matchbox_signaling/examples/client_server.rs
- matchbox_signaling/examples/full_mesh.rs
- matchbox_signaling/src/signaling_server/handlers.rs
- matchbox_signaling/src/topologies/client_server.rs
- matchbox_signaling/src/topologies/full_mesh.rs
- matchbox_socket/src/webrtc_socket/mod.rs
Resolves #253. Thanks for the excuse to try out [`ast-grep`](https://ast-grep.github.io/)
> Derive Display for PeerID

- examples/bevy_ggrs/src/main.rs
- matchbox_server/src/signaling.rs
- matchbox_signaling/src/topologies/client_server.rs
- matchbox_signaling/src/topologies/full_mesh.rs
- matchbox_socket/src/webrtc_socket/mod.rs
Just a bit of tidying up :broom:
> :broom: Simplify format strings

- matchbox_socket/src/webrtc_socket/socket.rs
> fix: receive() no longer blocks infinitely

- bevy_matchbox/Cargo.toml
- bevy_matchbox/examples/hello.rs
- bevy_matchbox/examples/hello_host.rs
- bevy_matchbox/examples/hello_signaling.rs
Adds some relatively minimal examples for `bevy_matchbox`
~~depends on #355 (will rebase when that one's in)~~
> Add examples for `bevy_matchbox`

- .github/dependabot.yml
> dependabot: Group minor and patch level PRs

- examples/bevy_ggrs/Cargo.toml
> Fix bevy_ggrs example not working on native

- Cargo.lock
- matchbox_socket/Cargo.toml
> Upgrade to webrtc-rs 0.10

- Cargo.lock
- README.md
- bevy_matchbox/Cargo.toml
- examples/bevy_ggrs/Cargo.toml
- examples/bevy_ggrs/src/box_game.rs
- examples/bevy_ggrs/src/main.rs
- matchbox_socket/Cargo.toml
> Upgrade to bevy 0.13

- .github/dependabot.yml
> Disable dependabot for cargo

- matchbox_protocol/src/lib.rs
> fix: error: direct implementation of `ToString`

- Cargo.lock
- matchbox_server/Cargo.toml
- matchbox_signaling/Cargo.toml
- matchbox_socket/Cargo.toml
> Upgrade dependencies, including webrtc 0.11

- bevy_matchbox/src/signaling.rs
- bevy_matchbox/src/socket.rs
New clippy warnings were causing ci to fail
> chore: cargo clippy --fix

- Cargo.lock
- examples/async_example/.cargo/config.toml
- examples/async_example/Cargo.toml
- examples/async_example/src/main.rs
- matchbox_socket/src/webrtc_socket/socket.rs
> Channel split and async example
