johanhelsing/matchbox

- matchbox_demo/src/main.rs
- matchbox_server/src/signaling.rs
Implements #13
This also allows to scope rooms with id.
I adapted a test to use scopes, but we might want to create separate tests rather than changing the existing one.
> #13: scoped rooms

- Cargo.lock
- matchbox_demo/Cargo.toml
- matchbox_demo/README.md
- matchbox_demo/src/box_game.rs
- matchbox_demo/src/main.rs
- matchbox_socket/Cargo.toml
- matchbox_socket/src/ggrs_socket.rs
As the title says.
matchbox_socket:
- updated to match ggrs 0.9 API
- removed the String <-> SocketAddr hack. this is almost the same as in branch `string-ids-wip`
matchbox_demo:
- updated to match ggrs 0.9 API
- repositioned the camera of the box game
- minor tweaks for the cube movement
Tested; runs with local matchbox_server. I did not experience the freezing after ~1 minute that we discussed on discord.
> update "ggrs_socket" feature and matchbox_demo to ggrs 0.9

- matchbox_demo/Cargo.toml
ggrs now requires the wasm-bindgen feature to be enabled to work
properly on wasm
> demo: Fix issues with disconnections after upgrading to ggrs 0.9.1

- Cargo.lock
- matchbox_socket/Cargo.toml
- matchbox_socket/src/webrtc_socket/native/message_loop.rs
Recently when building my game with a non-wasm target (MacOS in my case) compile failed with something like
webrtc-srtp-0.8.9/src/context/srtp.rs:82:43
|
82 |         let header = rtp::header::Header::unmarshal(&mut buf)?;
|                                           ^^^^^^^^^ function or associated item not found in `rtp::header::Header`
|
So there seemed to be some kind of version clash between dependencies of matchbox-socket
An upgrade of 'webrtc' in matchbox-socket's Cargo.toml fixed the issue for me. 
I had to remove a single line of code as well which addressed a field which didn't exist any more in the new version of the crate - I have no Idea what it was for but at least it compiles again :D
I don't use matchbox yet in my game for non-wasm target builds so I can't test at the …
> Upgrade version of webrtc dependency

- matchbox_socket/Cargo.toml
- matchbox_socket/src/webrtc_socket/mod.rs
- matchbox_socket/src/webrtc_socket/native/message_loop.rs
- matchbox_socket/src/webrtc_socket/wasm/message_loop.rs
This is an attempt to get cross data communication between native and WASM WebRTC, to address https://github.com/johanhelsing/matchbox/issues/47
The screenshot shows our own app using matchbox, 2 chrome tabs, 1 firefox tab, 2 desktop (native), all communicating with each other. We also tested order of launching and making sure no matter who offers or accepts it still connects. But this is all pretty tricky and might still have some bugs.
> cross native and wasm, ice trickle and data channel creation

- matchbox_socket/Cargo.toml
- matchbox_socket/src/webrtc_socket/native/message_loop.rs
- matchbox_socket/src/webrtc_socket/wasm/message_loop.rs
We had some hacks in place due to broken candidate serialization in webrtc-rs 0.4.
> Remove RtcIceCandidate hacks

- matchbox_socket/Cargo.toml
- matchbox_socket/src/webrtc_socket/wasm/message_loop.rs
Something in #54 broke connections between me and another peer (both of us behind NATs)
In this PR, we start sending null ice candidates, and add them on the receiving end. I'm not completely sure what the point of it is, but [MDN examples do this](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Simple_RTCDataChannel_sample) so it's probably best if we do it too.
Sadly, this alone wasn't enough to fix the regression. Adding back the wait for ice gathering to complete, however, did fix the issue. So that means that on wasm, we now have some weird frankenstein of ice-trickle and non-trickle, but the regression is gone, and cross-play still seems to work. So it's still better than before, and I'm really anxious to get a fix for the regression merged, even if it's ugly and I don't …
> Fix regression in wasm connections behind NATs

- matchbox_socket/src/lib.rs
- matchbox_socket/src/webrtc_socket/mod.rs
- matchbox_socket/src/webrtc_socket/native/message_loop.rs
- matchbox_socket/src/webrtc_socket/wasm/message_loop.rs
Exploring your suggestions in #63 regarding #25 I tried an alternative implementation.
The two main differences beside some fixes are:
1) It is possible to receive a packet and at the same time understand from which channel it came
2) I use vectors instead of tuples to prepare for a later extension of the feature for more than two data channels
I decided to open two PRs for both variants because I am not sure which one is better. I like the simplicity of #63 and I tried to keep it in this PR - it is still possible to simply use the send() and receive() methods to not have to worry about the big world of WebRTC at all and remain blissfully oblivious of the data channels used backstage.
If the library user would like to have more influence or information over how the packet is or was sent I …
> Support multiple reliable and unreliable data channels

- matchbox_socket/src/webrtc_socket/mod.rs
Simple convenience for sending to all connected peers
> Add `WebRtcSocket::broadcast_on_channel`

- .github/workflows/ci.yml
We want to run github actions on pull requests, not just on pushes, because the pull_request event actually performs the merge to the target branch.
This means if a branch started on an old main, we will still catch potential incompatible changes that don't show up as merge conflicts.
Keeping the push events as well for now, as public github actions is free for public repos. If this changes, we should probably remove the push events except on main and tags.
#71
> Run github actions ci workflow on pull_request events

- matchbox_demo/src/main.rs
Fix `clippy` lints by inlining `remaining` players in waiting message
> Inline format argument

- matchbox_server/src/signaling.rs
Extract a tuple of `impl Reply` from `Filter` instead of bare `impl Reply`
> Fix inferred bound warning

- Cargo.lock
- matchbox_server/Cargo.toml
- matchbox_server/src/error.rs
- matchbox_server/src/main.rs
- matchbox_server/src/signaling.rs
- matchbox_simple_demo/src/main.rs
It's no secret Warp is losing the server framework battle to Axum, so this will be the first step towards modernizing the architecture.
This is a draft to replace Warp with Axum for the signalling server. Another opinion I made was to use `tracing`/`tracing_subscriber` over `pretty_env_logger` for logging, for similar reasons.
This is a total drop-in replacement. All metrics being logged and all route rules are preserved, with no impact to demos or the user.
> Replace Warp with Axum for the signalling server

- matchbox_server/src/signaling.rs
- matchbox_simple_demo/src/main.rs
- matchbox_socket/src/webrtc_socket/messages.rs
- matchbox_socket/src/webrtc_socket/mod.rs
- matchbox_socket/src/webrtc_socket/native/message_loop.rs
- matchbox_socket/src/webrtc_socket/wasm/message_loop.rs
This is one way of handling disconnected peers that seems to work in our case. For issue #81 
Calling:
`pub fn disconnected_peers(&mut self) -> Vec<PeerId> `
cleans up peers and returns disconnected peers. Needs to be called any time the API user wants to clean up peers.
Not sure how to handle when GGRS takes over the socket. Could potentially handle this in `log_ggrs_events` if the socket is accessible.
Anyway, just a possible solution.
> a possible way of handling disconnected peers

- Cargo.lock
- matchbox_socket/Cargo.toml
- matchbox_socket/src/error.rs
- matchbox_socket/src/lib.rs
- matchbox_socket/src/webrtc_socket/error.rs
- matchbox_socket/src/webrtc_socket/mod.rs
- matchbox_socket/src/webrtc_socket/native/signalling_loop.rs
- matchbox_socket/src/webrtc_socket/wasm/signalling_loop.rs
This PR is very focused on solving #93, but would also lay the groundwork for error propagation in support of #91 and #5.
I wish to "fail fast" if this method of error propagation is undesired, although I don't note anything controversial (avoiding another "second thoughts" re: #88). If this is approved I'll begin work on further error propagation.
In summary:
- Matchbox gets a root level `Error` type.
- The error library chosen is `thiserror`, to keep parity with the `matchbox_server`'s error library.
- WASM/Native Errors are configured in `webrtc_socket/error.rs` and enabled through cfg-directives (cfg-if would help here).
> Begin error propogation

- matchbox_socket/src/webrtc_socket/mod.rs
- matchbox_socket/src/webrtc_socket/wasm/message_loop.rs
We should perhaps just replace our `JsError` with `gloo_utils::errors::JsError`, but before that, this at least makes it slightly less hacky without introducing a dependency and easier to see what's really needed/going on.
> Minor cleanups

- Cargo.lock
- matchbox_socket/Cargo.toml
WebRTC 0.6 is currently kind of broken. It doesn't currently build if you add it as a dependency, I get errors about multiple versions:
```
error[E0308]: mismatched types
--> C:\Users\Johan\.cargo\registry\src\github.com-1ecc6299db9ec823\webrtc-0.6.0\src\data_channel\mod.rs:180:60
|
180 | ...      let dc = data::data_channel::DataChannel::dial(&association, self.id(), cfg).await?;
|                   ------------------------------------- ^^^^^^^^^^^^ expected `Association`, found a different `Association`
|                   |
|                   arguments to this function are incorrect
|
= note: `Association` and `Association` have similar names, but are actually distinct types
note: `Association` is defined in crate `webrtc_sctp`
--> …
```
> Upgrade to webrtc 0.7

- matchbox_demo/src/main.rs
- matchbox_server/src/signaling.rs
- matchbox_simple_demo/src/main.rs
- matchbox_socket/src/ggrs_socket.rs
- matchbox_socket/src/webrtc_socket/error.rs
- matchbox_socket/src/webrtc_socket/messages.rs
- matchbox_socket/src/webrtc_socket/mod.rs
- matchbox_socket/src/webrtc_socket/native.rs
- matchbox_socket/src/webrtc_socket/socket.rs
- matchbox_socket/src/webrtc_socket/wasm.rs
Thought `matchbox_server` should be the one to produce the `PeerId` then saw a comment with the same idea :laughing:
Currently don't make the `PeerId` super available in the client, but also don't yet have a need
> Have server produce `PeerId`

- matchbox_socket/src/webrtc_socket/error.rs
- matchbox_socket/src/webrtc_socket/mod.rs
- matchbox_socket/src/webrtc_socket/native.rs
- matchbox_socket/src/webrtc_socket/wasm.rs
Had a go at abstracting the `message_loop` implementation via a series of `Messenger` trait functions
> Abstract message loop implementation

- Cargo.lock
- matchbox_socket/Cargo.toml
After #111 , we don't actually need `uuid` in the socket crate.
> Remove `uuid` dependency

- matchbox_socket/src/webrtc_socket/native.rs
- matchbox_socket/src/webrtc_socket/socket.rs
- matchbox_socket/src/webrtc_socket/wasm.rs
Some relatively minor and uncontroversial improvements to code quality and logging.
- Uses the new `"info!("format string: {variable}");` form for logging
- `data channel` instead of `channel` in log messages and variables to be more clear
- Renamed some variables that lacked plural form
- Send `()` instead of `u8` when we don't care about payload
- Be less hyperbolic in log messages
> Improve logging and code clarity

- README.md
Makes it easier to find the actual code, as you go directly to a view where you see both the example source files and its readme at the same time.
Maybe helps #148 a tiny bit? (Should be easy to find the documentation you're looking for)
> docs: Link to example folders, not READMEs

- examples/bevy_ggrs/src/main.rs
- matchbox_protocol/src/lib.rs
- matchbox_socket/src/ggrs_socket.rs
I found out we can actually return a valid player even if we don't have an id, since there shouldn't be any other peers at that point ,we don't need the sort, and consequently not the id.
> Remove `UnknownPeerId` error

- examples/bevy_ggrs/src/main.rs
- examples/simple/src/main.rs
- matchbox_socket/src/ggrs_socket.rs
- matchbox_socket/src/lib.rs
- matchbox_socket/src/webrtc_socket/error.rs
- matchbox_socket/src/webrtc_socket/mod.rs
- matchbox_socket/src/webrtc_socket/socket.rs
Again, with a view towards making multi-channel sockets easier to use, I've abstracted channels by implementing a `WebRtcChannel` struct which provides `send` & `receive`. This should make the code from @johanhelsing's [last devblog](https://johanhelsing.studio/posts/cargo-space-devlog-6) a lot cleaner.
Unfortunately I've had to drop `broadcast` as it would require channels to know about their peers, it wasn't in use anywhere as far as I can tell, though maybe we should still figure out a way of re-adding it
> Provide abstraction for a channel

- .github/workflows/ci.yml
Adds the [rust-cache action](https://github.com/Swatinem/rust-cache) to our CI steps to cache dependency download & incremental compilation
> Use `rust-cache` to speed up CI

- .github/workflows/code.yml
- .github/workflows/markdown-lint.yml
Splits the one CI job into two, one for Code CI and one for linting markdown. Just makes the CI a bit easier to understand and brings consistency with #163
> Split CI into Code & Markdown Lint

- matchbox_socket/src/webrtc_socket/mod.rs
- matchbox_socket/src/webrtc_socket/socket.rs
Just resolving a todo, don't think people will actually need to change this, except for satisfying their need for premature optimization.
> Add `signaling_keep_alive_interval` to socket builder

- .github/workflows/code.yml
Adds the `--all-targets` argument to `cargo check` in the Code CI to check non-default targets (e.g. examples & benches)
> Check all targets in CI

- README.md
- examples/bevy_ggrs/Cargo.toml
- matchbox_socket/Cargo.toml
- matchbox_socket/src/lib.rs
The common convention seems to be that crate integration features should just be named after the crate they integrate with.
https://rust-lang.github.io/api-guidelines/naming.html#feature-names-are-free-of-placeholder-words-c-feature
Also, gets rid of a dash. Otherwise, I think we're entirely in camp understcore, like Bevy.
> Rename `ggrs-socket` feature to `ggrs`

- bevy_matchbox/src/lib.rs
- matchbox_socket/src/webrtc_socket/socket.rs
This is a hopefully non-controversial start for #175 ,  just make sure it's possible to use the extension, and add a doctest so it's easy to see resulting usage for the implemented API
We could perhaps discuss erasing the type etc. in follow-u prs.
> Make `close_socket` command extension usable

- matchbox_socket/src/webrtc_socket/socket.rs
I think taking channels out is probably a bit uncommon, would probably be nice to provide the discussed panicky convenience.
> Add `get_channel`, make `channel` panicky

- matchbox_server/src/signaling.rs
- matchbox_signaling/tests/client_server.rs
- matchbox_signaling/tests/full_mesh.rs
I'm not really sure what the deal is, but when running the tests, I get panics from every signaling test, unless I only bind to localhost...
```
---- signaling::tests::signal stdout ----
thread 'signaling::tests::signal' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 10049, kind: AddrNotAvailable, message: "The requested address is not valid in its context." })', matchbox_server\src\signaling.rs:394:18
```
However, I *don't* get this error in the examples. Maybe something is off in my windows firewall settings. Do the tests run on windows for either of you?
> Make tests pass on windows

- bevy_matchbox/src/lib.rs
Ass ability to:
- Create a `MatchboxSocket` for direct insertion as a `Resource`
- Use `MatchboxSocket` as a `Component`
Todo:
- Utilities for `MatchboxSocket` as a `Component`
> Expand bevy plugin usage options

- matchbox_socket/src/webrtc_socket/mod.rs
A straightforward fix for the issue with handshake channels being closed while receiving the signal.
Fixes #183
> Fix panic when signal is received after handshake was completed

- matchbox_socket/Cargo.toml
Fixes a build error when building for wasm with the `ggrs` feature.
> Add missing `ggrs/wasm-bindgen` dependency for `ggrs` feature

- Cargo.lock
- matchbox_socket/Cargo.toml
We had a pretty bad regression in #183, and one accidentally private error type, and a missing feature dependency in `ggrs` on wasm.
Let's do a point release for `matchbox_socket` only.
Otherwise, it should be just doc/ci changes (see https://github.com/johanhelsing/matchbox/compare/v0.6.0...release-0.6.1).
> Release `matchbox_socket` v0.6.1

- .github/workflows/code.yml
Give `server-container` permission to write to packages and login as repository owner instead of actor.
Fixes: #213
> fix: ci server image push

- README.md
I've recently released lavagna, a collaborative blackboard. I loved how easy it was integrating WebRTC on my project with matchbox. Many thanks! I feel `lavagna` can be under the *Showcase* section of matchbox README.
> Add lavagna to Showcase

- bevy_matchbox/src/socket.rs
> Move task handle into bevy Resource / Component

- matchbox_socket/src/lib.rs
- matchbox_socket/src/webrtc_socket/error.rs
- matchbox_socket/src/webrtc_socket/socket.rs
A simplified example of what I was trying to achieve that illustrates the issue at hand.
```rust
loop {
// Something that calls `WebRtcSocket.update_peers()` in the background.
connection.register_peers();
if connection.connected_peers_count() == 0 {
info!("Waiting for a connection.");
futures_timer::Delay::new(Duration::from_millis(500)).await;
continue;
}
connection.send(...);
}
```
At glance this look fine, but this snippet will cause an infinite loop if the connection is broken. This is because `WebRtcSocket.update_peers()` silently "fails" when that is the case.
This draft implements a `try_update_peers()` that simply returns a `Result<Vec<(PeerId, PeerState)>, &'static str>`, where the static is  "Channel closed".
I haven't yet added any documentation nor tests, as several error …
> `WebRtcConnection.update_peers()` error handling.

- Cargo.lock
- matchbox_signaling/Cargo.toml
- matchbox_signaling/tests/client_server.rs
- matchbox_signaling/tests/full_mesh.rs
Use channels instead of atomics for tests.
Fixes: #260
> Fix flaky signaling tests

- matchbox_server/Dockerfile
It had errors with missing glibc on launch
> Fix broken matchbox_server docker image

- matchbox_socket/src/webrtc_socket/socket.rs
A clippy lint is triggered because `.into_iter()` is needlessly being called on a value.
> Fix a clippy lint

- matchbox_signaling/src/error.rs
- matchbox_signaling/src/signaling_server/error.rs
- matchbox_socket/src/error.rs
- matchbox_socket/src/webrtc_socket/error.rs
The error types defined using `#[derive(thiserror::Error)]` do not include the error message from any inner wrapped errors, which makes it very difficult to debug any errors that occur while using this crate.
This PR simply changes the macro-generated error messages to include the inner errors.
> Add more information to error messages

- matchbox_socket/src/webrtc_socket/native.rs
- matchbox_socket/src/webrtc_socket/wasm.rs
Closes #280 
The root cause of the issue is, when a native client receives ICE candidates from a WASM client, a "null" is sent as the terminating signal to delineate the end of candidates.
This is expected behavior, but is logged as an error for native.
This ensures the same behavior exists on web/native.
> Don't log null ice candidates as errors on native

- matchbox_socket/src/webrtc_socket/native.rs
Problem:
The default RTCIceCredentialType [is `Unspecified`](https://github.com/webrtc-rs/webrtc/blob/master/webrtc/src/ice_transport/ice_credential_type.rs#L9-L10) and that will eventually end up crashing when [used here](https://github.com/johanhelsing/matchbox/blob/main/matchbox_socket/src/webrtc_socket/native.rs#L124-L126) because the return value will be Err since [this](https://github.com/webrtc-rs/webrtc/blob/71157ba2153a891a8cfd819f3cf1441a7a0808d8/webrtc/src/ice_transport/ice_server.rs#L52)
This PR will default to `RTCIceCredentialType::Password`. I don't know if that's what you would prefer, but it fixes my problem :)
> Add missing RTCIceCredentialType to the RTCIceServer

- examples/bevy_ggrs/Cargo.toml
We switched to webgpu by accident when upgrading to Bevy 0.11.
In Bevy 0.11 webgl2 is still default, but not when disabling default features.
It's not working properly everywhere yet, so switch back to webgl2, at least until it's default in bevy.
> Use webgl for bevy_ggrs example

- bevy_matchbox/src/signaling.rs
bevy_matchbox with signalling feature doesn't compile otherwise
> Command::apply, not write - fix bevy_matchbox with signaling feature

- .github/workflows/code.yml
- bevy_matchbox/src/signaling.rs
> Test bevy signaling

- matchbox_server/Dockerfile
Current dockerfile cannot run on ARM because builder use different GLIB version with runner 
This commit change builder to the same tag as runner
> Fix GLIB version not match in ARM

- Cargo.lock
- examples/bevy_ggrs/Cargo.toml
And remove unnecessary bevy features
Before:
After:
> Fix pink materials in bevy_ggrs example

- matchbox_server/Dockerfile
Will make our docker images smaller
> Fix unnecessary caching of `/var/lib/apt/lists/*` in `Dockerfile`

- matchbox_signaling/Cargo.toml
Previously, running `cargo run --example client_server` from within `matchbox_signaling` would result in 
```
Compiling matchbox_signaling v0.7.0 (C:\Users\Johan\dev\matchbox\matchbox_signaling)
error[E0433]: failed to resolve: could not find `EnvFilter` in `tracing_subscriber`
--> matchbox_signaling\examples\client_server.rs:29:33
|
29 |             tracing_subscriber::EnvFilter::try_from_default_env()
|                                 ^^^^^^^^^ could not find `EnvFilter` in `tracing_subscriber`
For more information about this error, try `rustc --explain E0433`.
error: could not compile `matchbox_signaling` (example "client_server") due to previous error
```
> Add missing `env-filter` feature for signaling examples

- Cargo.lock
- bevy_matchbox/Cargo.toml
- bevy_matchbox/src/signaling.rs
- matchbox_server/src/topology.rs
- matchbox_signaling/src/error.rs
- matchbox_signaling/src/signaling_server/builder.rs
- matchbox_signaling/src/signaling_server/server.rs
- matchbox_signaling/tests/client_server.rs
- matchbox_signaling/tests/full_mesh.rs
Alternative to #352 
Axum expects being run in a tokio context, but Bevy isn't that. Use the same approach as we do for `matchbox_socket`, and wrap the async call using `async-compat`
Moves binding to an explicit optional step, and makes `Server::local_addr` return an `Option<SocketAddr>`
Fixes #350
> Fix bevy matchbox signaling panic

- .github/workflows/lint-toml.yml
Previously it would just error, but not tell you why.
> ci: Explain why toml linting fails

- Cargo.lock
- bevy_matchbox/Cargo.toml
- examples/bevy_ggrs/Cargo.toml
- examples/bevy_ggrs/src/box_game.rs
- examples/bevy_ggrs/src/main.rs
- matchbox_signaling/Cargo.toml
- matchbox_socket/Cargo.toml
Make the minimum changes required to support Bevy 0.12 and the latest version of Bevy GGRS.
- Switched to Git version of GGRS
- Switched to Git version of Bevy GGRS
- Updated Box Game example to match newer Bevy GGRS API.
I've switched to Git versions of GGRS and Bevy GGRS. For a proper release, these should be changed to specific released versions.
> Updated to Bevy 0.12 and latest Bevy GGRS

- matchbox_socket/src/ggrs_socket.rs
This PR makes the `WebRtcSocket::players()` method available for `WebRtcSocket<MultipleChannels>` types as well.
> Make `WebRtcSocket::players()` available for `MultipleChannels` sockets

- .github/workflows/code.yml
- .github/workflows/lint-toml.yml
- .github/workflows/markdown-lint.yml
There was a minimal difference between a push and a pull_request PR runs on stale branches, but branches based off of main, it would test exactly the same code twice.
As far as I understand, testing the pull request event is best, since it does a merge first, before testing.
> ci: Don't run twice on pushes to PR branches

- matchbox_socket/src/webrtc_socket/socket.rs
Fixes a regression on WASM where if the peer hung-up in the middle of a connection, it would leave the wasm peer in a reproducible panic condition.
Fixes #391
> fix: issue 391

- examples/bevy_ggrs/Cargo.toml
fixes https://github.com/johanhelsing/matchbox/issues/398
This fix is only for WASM. The native compilation is still broken as per https://github.com/johanhelsing/matchbox/issues/417
Seems that this was forgotten, because the dependency was added for bevy_matchbox
https://github.com/AgustinRamiroDiaz/matchbox/blob/a70b27a5291cf0427e4312c75d6529625fe3e970/bevy_matchbox/Cargo.toml#L50
> fix: [bevy_ggrs example] add tonemapping_luts bevy feature

- Cargo.lock
- matchbox_server/Cargo.toml
- matchbox_server/src/main.rs
- matchbox_signaling/Cargo.toml
- matchbox_signaling/src/error.rs
- matchbox_signaling/src/signaling_server/builder.rs
- matchbox_signaling/src/signaling_server/server.rs
Hyper (and by extension axum) removed the `Server` struct on 1.0, this largely keeps the same API but uses axum::serve under the hood. However bind is now an async function, and the errors are slightly different.
Closes #397.
> Update to axum-0.7/hyper-1.2

- bevy_matchbox/src/socket.rs
After rust 1.77 we started getting warnings about an unused task handle. Looking at previous code, I'm pretty sure we take ownership because we don't want to drop the task before the socket, and we also want to be able to drop the task *when* we want to.
Fixes: #437
> Fix new warnings in rust 1.77

- Cargo.lock
- matchbox_socket/Cargo.toml
This wasn't used and is deprecated due to causing cyclic dependency issues.
Ran into this and it took a while to realise this was the source of the issue, see this thread for more discussion on it: https://github.com/tkaitchuck/aHash/issues/95
> Remove serde-serialize feature

- .github/workflows/code.yml
- bevy_matchbox/src/signaling.rs
> ci: Run clippy with signaling feature enabled

- Cargo.lock
- bevy_matchbox/Cargo.toml
- bevy_matchbox/src/signaling.rs
- bevy_matchbox/src/socket.rs
- examples/bevy_ggrs/Cargo.toml
- examples/bevy_ggrs/src/box_game.rs
- examples/bevy_ggrs/src/main.rs
- matchbox_socket/Cargo.toml
Fixes #454.
This PR is an upgrade to [Bevy 0.14](https://bevyengine.org/news/bevy-0-14/). I opened this in draft for now, as it depends on my own branch for `bevy_ggrs` since we seem to be blocked on them updating first. See https://github.com/gschup/bevy_ggrs/pull/111.
The changes are pretty trivial, just version bumps (also updated `serde_qs` while we're at it), an added `bevy_state` feature for Bevy, and some color and meshing changes.
> Update `bevy_matchbox` to Bevy 0.14

- bevy_matchbox/examples/hello_host.rs
- bevy_matchbox/examples/hello_signaling.rs
Added a reference in the bevy_matchbox example's {hello_host, hello_signaling} comment header to advise updating the local Cargo.toml to enable the necessary features for seamless integration with the example logic.
> bevy_matchbox example header comments to include reference to cargo dependency changes when needed for integration.

- .github/workflows/code.yml
Avoid having to bump manually + gets rid of dependabot noise
> Depend on rust-cache v2 floating tag for easier maintenance

- matchbox_signaling/src/signaling_server/builder.rs
- matchbox_signaling/tests/full_mesh.rs
If you want to use a single server and have matchbox signalling at a specific route it's useful to be able to get the router directly and work with that. You can't use `mutate_router` as that occurs before the final router construction and you'll likely end up with conflicting routes. I don't think you can expose a constructed `IntoMakeServiceWithConnectInfo` as that can't be merged/nested into another router, it just has to be called at the root level before use.
Open to other suggestions to how to do this, but this seems like the most straight forward and flexible way to do it.
I also loosened the traits for `mutate_router` which I didn't end up needing, but it is more restrictive than necessary.
> Add construct_router function

- bevy_matchbox/examples/hello.rs
- bevy_matchbox/examples/hello_host.rs
- bevy_matchbox/src/lib.rs
- bevy_matchbox/src/signaling.rs
- bevy_matchbox/src/socket.rs
- examples/bevy_ggrs/src/box_game.rs
- examples/bevy_ggrs/src/main.rs
- examples/error_handling/src/main.rs
- examples/simple/src/main.rs
- matchbox_socket/src/ggrs_socket.rs
- matchbox_socket/src/lib.rs
- matchbox_socket/src/webrtc_socket/mod.rs
- matchbox_socket/src/webrtc_socket/native.rs
- matchbox_socket/src/webrtc_socket/socket.rs
The typestate pattern caused a lot of boilerplate w.r.t. both the implementation and the usage of matchbox socket.
There appeared to be only three actual uses of the typestate pattern:
* Preventing client code from calling build() without adding a channel.
* Some convenience methods to read/write from the first channel in the case where where was only one channel.
* Making sure that ggrs::NonBlockingSocket is only implemented for
WebRtcSocket in the case where it is a single channel socket, to avoid the case where a reliable socket is accidentally used as a GGRS socket (or a unreliable socket is used for GGRS + some other data).
The first and (mostly) the last points can be accomplished at runtime via asserts, and owing to the "set it up and use it from one place" nature of this library I …
> Refactor: Drop typestate pattern for building sockets

- Cargo.lock
- matchbox_socket/Cargo.toml
- matchbox_socket/src/webrtc_socket/socket.rs
This PR adds an async api:
- implement `Sink` and `Stream` for `WebRtcChannel`
- add type `RawPeerChannel` with `AsyncRead` and `AsyncWrite` support
- add functions `take_raw` and `take_raw_by_id` on `WebRtcSocket`
Closes: #453
> feat: add async api

- Cargo.lock
- README.md
- bevy_matchbox/Cargo.toml
- bevy_matchbox/src/signaling.rs
- bevy_matchbox/src/socket.rs
- examples/bevy_ggrs/Cargo.toml
- examples/bevy_ggrs/src/box_game.rs
- examples/bevy_ggrs/src/main.rs
- matchbox_socket/Cargo.toml
This is blocked by bevy_ggrs, but I thought I might get the ball rolling somewhat to speed up the overall process. I put temporary deps to my fork of bevy_ggrs, which I used for the upgrade PR.
Like I said in my [bevy_ggrs](https://github.com/gschup/bevy_ggrs/pull/113) PR, I'm not a 100% certain I got it right. Everything compiles, tests pass, clippy is happy and I got the hello example to work just fine, which gives me a lot of hope, but I'm still not confident. Please review carefully.
Hope this helps with the upgrade.
> Upgrade to bevy 0.15

- matchbox_server/src/state.rs
- matchbox_server/src/topology.rs
Hello, i noticed that a peer matched by  a `next?` never receives disconnected event.
From what I understand in the codebase, this happens because the room is purged once all peers have joined (likely to make space for the next clients)., thus making disconnected peers never able to notify others in that room.
This PR addresses the issue by saving the full list of room peers before purging it, allowing those events to be sent later.
This may not be the best way to handle this, let me know if any changes are needed!
> Feature request : support Disconnect event for room matched by "next?" 

- Cargo.lock
- examples/async_example/.cargo/config.toml
- examples/async_example/Cargo.toml
- examples/async_example/src/main.rs
- matchbox_socket/src/webrtc_socket/socket.rs
close https://github.com/johanhelsing/matchbox/issues/482
Adds method to obtain the channels that make up a WebRTC channel. Without this, you cannot read and write concurrently using async.
```rs
impl WebRtcChannel {
/// Split the channel into a reader and writer.
/// Useful for concurrently sending and receiving messages using async code.
pub fn split(
self,
) -> (
UnboundedSender<(PeerId, Packet)>,
UnboundedReceiver<(PeerId, Packet)>,
) {
(self.tx, self.rx)
}
```
Adds simple example showcasing full mesh ping pong spam.
Through, now I think of it a bit more, you don't even need an async sender, the channels are unbounded, so you can send everything using only sync, and read everything using async. Still, without extra methods, you can't clone out the sender and put it on a different …
> channel split() method + async example

- Cargo.lock
- bevy_matchbox/Cargo.toml
- bevy_matchbox/examples/hello.rs
- bevy_matchbox/examples/hello_host.rs
- bevy_matchbox/examples/hello_signaling.rs
- bevy_matchbox/src/signaling.rs
- bevy_matchbox/src/socket.rs
Bevy 0.16 was released a few days ago, update `bevy_matchbox` to use that.
There weren't any major changes affecting matchbox that I could see.
The only things I had to adjust to were:
- `utils::Duration` was removed in favor of `core::Duration`: https://github.com/bevyengine/bevy/pull/17158
- Logging now requires a feature
- `ecs::world::Command` moved to `prelude::Command`
See: https://bevyengine.org/news/bevy-0-16/.
> Update to bevy 0.16

- .github/workflows/code.yml
- bevy_matchbox/src/socket.rs
- examples/async_example/src/main.rs
- examples/bevy_ggrs/src/box_game.rs
- examples/custom_signaller/src/main.rs
This PR addresses the following:
* Fixes a failing doc test in `bevy_matchbox`: The api of `single()` now returns a `Result<>` instead of panicking.
* Enables doc test execution in CI to ensure that any future regressions in code examples within the documentation are caught automatically by CI, preventing outdated or broken examples from being published.
* Fixes clippy lints triggered by CI
> Fix `bevy_matchbox` doc test & include doc tests in CI
